#!/bin/sh -e
#
# Finish up the installation

#DEBHELPER#

# Source debconf library.
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]
then
    # Install files in user folders
    #
    for u in /root /home/*
    do
        if ! test -f "${u}/.lessfilter"
        then
            cp /usr/share/alex-tools/.lessfilter "${u}/.lessfilter"
            chmod 700 "${u}/.lessfilter"
        fi
    done
fi

# vim: ts=4 sw=4 et nocindent
